#! /bin/bash

"$(dirname "$0")"/src/plan "$DOMAIN" "$PROBLEM" ipc unsat-sym --plan-file "$PLAN_FILE"

last=`awk '/./{line=$0} END{print line}' log`

if [[ "$last" == "unsolvable" ]];
then
	echo $last
else if [[ "$last" == "solvable" ]];
then
    echo $last
else
	echo "unknown"
fi
fi
